#############################################################################
# Makefile for building: piet
# Generated by qmake (2.01a) (Qt 4.3.4) on: wt. wrz 15 17:34:38 2009
# Project:  piet.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile piet.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SHARED -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -fpermissive -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Isrc/core -Isrc -I. -I.
LINK          = g++
LFLAGS        = -Wl,--no-undefined
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/test.cpp \
		src/core/pblockmanager.cpp \
		src/core/pcalcstack.cpp \
		src/core/pcodepointer.cpp \
		src/core/pcodestats.cpp \
		src/core/pcolormanager.cpp \
		src/core/pconsole.cpp \
		src/core/pvirtualmachine.cpp 
OBJECTS       = obj/test.o \
		obj/pblockmanager.o \
		obj/pcalcstack.o \
		obj/pcodepointer.o \
		obj/pcodestats.o \
		obj/pcolormanager.o \
		obj/pconsole.o \
		obj/pvirtualmachine.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		piet.pro
QMAKE_TARGET  = piet
DESTDIR       = 
TARGET        = piet

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: piet.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf
	$(QMAKE) -unix -o Makefile piet.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile piet.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/piet1.0.0 || $(MKDIR) .tmp/piet1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/piet1.0.0/ && $(COPY_FILE) --parents src/debug.h src/core/pblockmanager.h src/core/pcalcstack.h src/core/pcodepointer.h src/core/pcodestats.h src/core/pcolormanager.h src/core/pconsole.h src/core/penums.h src/core/pstructs.h src/core/pvirtualmachine.h .tmp/piet1.0.0/ && $(COPY_FILE) --parents src/test.cpp src/core/pblockmanager.cpp src/core/pcalcstack.cpp src/core/pcodepointer.cpp src/core/pcodestats.cpp src/core/pcolormanager.cpp src/core/pconsole.cpp src/core/pvirtualmachine.cpp .tmp/piet1.0.0/ && (cd `dirname .tmp/piet1.0.0` && $(TAR) piet1.0.0.tar piet1.0.0 && $(COMPRESS) piet1.0.0.tar) && $(MOVE) `dirname .tmp/piet1.0.0`/piet1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/piet1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

obj/test.o: src/test.cpp src/core/pvirtualmachine.h \
		src/core/penums.h \
		src/core/pstructs.h \
		src/core/pconsole.h \
		src/core/pblockmanager.h \
		src/core/pcodepointer.h \
		src/core/pcolormanager.h \
		src/core/pcalcstack.h \
		src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/test.o src/test.cpp

obj/pblockmanager.o: src/core/pblockmanager.cpp src/core/pblockmanager.h \
		src/core/penums.h \
		src/core/pstructs.h \
		src/core/pcodepointer.h \
		src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/pblockmanager.o src/core/pblockmanager.cpp

obj/pcalcstack.o: src/core/pcalcstack.cpp src/core/pcalcstack.h \
		src/core/penums.h \
		src/core/pstructs.h \
		src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/pcalcstack.o src/core/pcalcstack.cpp

obj/pcodepointer.o: src/core/pcodepointer.cpp src/core/pcodepointer.h \
		src/core/penums.h \
		src/core/pstructs.h \
		src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/pcodepointer.o src/core/pcodepointer.cpp

obj/pcodestats.o: src/core/pcodestats.cpp src/core/pcodestats.h \
		src/core/penums.h \
		src/core/pstructs.h \
		src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/pcodestats.o src/core/pcodestats.cpp

obj/pcolormanager.o: src/core/pcolormanager.cpp src/core/pcolormanager.h \
		src/core/penums.h \
		src/core/pstructs.h \
		src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/pcolormanager.o src/core/pcolormanager.cpp

obj/pconsole.o: src/core/pconsole.cpp src/core/pconsole.h \
		src/core/penums.h \
		src/core/pstructs.h \
		src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/pconsole.o src/core/pconsole.cpp

obj/pvirtualmachine.o: src/core/pvirtualmachine.cpp src/core/pvirtualmachine.h \
		src/core/penums.h \
		src/core/pstructs.h \
		src/core/pconsole.h \
		src/core/pblockmanager.h \
		src/core/pcodepointer.h \
		src/core/pcolormanager.h \
		src/core/pcalcstack.h \
		src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/pvirtualmachine.o src/core/pvirtualmachine.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

